# Generated by Django 3.1.7 on 2021-02-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('material', models.TextField(blank=True, null=True, verbose_name='Материал')),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=10000000, verbose_name='Цена закупочная')),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10000000, verbose_name='Цена продажи')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Изображение')),
                ('number', models.CharField(default='05', max_length=5, verbose_name='Номер региона')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.item', verbose_name='Связанный товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название категории')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.category', verbose_name='Родительская категория')),
            ],
        ),
    ]
