# Generated by Django 3.1.7 on 2021-02-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_itemimage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_buy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000000, null=True, verbose_name='Цена закупочная'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_sell',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000000, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item.region', verbose_name='Регион'),
        ),
    ]
